-- -- ======================
-- -- USER ADDRESSES
-- -- ======================
-- CREATE TABLE addresses (
--   address_id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   user_id      INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
--   shipping_address_line1  VARCHAR(255),
--   shipping_address_line2  VARCHAR(255),
--   shipping_city_state     VARCHAR(255),
--   created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
-- );

-- CREATE INDEX idx_addresses_user ON addresses(user_id);